## PyTorch exercises

### Tensors

1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]
5. Perform a matrix multiplication of two tensors of size (2, 4) and (4, 2). Then do it in-place.
6. Do element-wise multiplication of two randomly filled $(n_1,n_2,n_3)$ tensors. Then store the result in an Numpy array.


In [1]:
import torch
import numpy as np
import torchvision 
from torchvision import transforms 

In [15]:
tensor1 = torch.rand(2, 17)
tensor1

tensor([[0.5590, 0.0749, 0.3035, 0.1637, 0.3963, 0.5464, 0.0523, 0.8547, 0.6673,
         0.2143, 0.5703, 0.4390, 0.5805, 0.6740, 0.4651, 0.5275, 0.5268],
        [0.2066, 0.7508, 0.2743, 0.3310, 0.9022, 0.1848, 0.0211, 0.1161, 0.0356,
         0.4025, 0.5039, 0.9450, 0.3961, 0.8559, 0.2264, 0.3810, 0.2165]])

In [17]:
tensor2 = torch.FloatTensor(3, 1)
tensor2

tensor([[8.4773e-22],
        [2.1510e-42],
        [0.0000e+00]])

In [19]:
tensor3 = torch.LongTensor(5, 2 , 1)
tensor3

tensor([[[6593253343392],
         [            0]],

        [[            0],
         [            0]],

        [[            0],
         [            0]],

        [[            0],
         [            0]],

        [[            0],
         [            0]]])

In [21]:
tensor3.fill_(7)

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])

In [36]:
tensor4 = torch.ByteTensor(5)
tensor4

tensor([  0,   0, 128,  63,   0], dtype=torch.uint8)

In [40]:
tensor4[1:4] = 1
tensor4

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)

In [42]:
tensor1 = torch.rand(2,4)
tensor2 = torch.rand(4,2)
torch.mm(tensor1, tensor2)

tensor([[0.8564, 0.4262],
        [0.1525, 0.0694]])

In [44]:
result_inplace = torch.empty(2, 2)
torch.mm(tensor1, tensor2, out=result_inplace)

tensor([[0.8564, 0.4262],
        [0.1525, 0.0694]])

In [52]:

tensor1 = torch.rand(1, 3, 3)
tensor2 = torch.rand(3, 3, 1)

res = torch.mul(tensor1, tensor2)
result_numpy = res.numpy()
print(result_numpy)

[[[0.02399996 0.02687856 0.02379905]
  [0.29751584 0.23353992 0.23609522]
  [0.02470416 0.35034734 0.01777468]]

 [[0.55674607 0.6235233  0.5520855 ]
  [0.17234457 0.13528469 0.13676491]
  [0.01454399 0.20625865 0.01046442]]

 [[0.47270304 0.5294     0.468746  ]
  [0.6054485  0.4752567  0.48045677]
  [0.00382091 0.05418701 0.00274915]]]


### Forward-prop/backward-prop
1. Create a Tensor that `requires_grad` of size (5, 5).
2. Sum the values in the Tensor.
3. Multiply the tensor by 2 and assign the result to a new python variable (i.e. `x = result`)
4. Sum the variable's elements and assign to a new python variable
5. Print the gradients of all the variables
6. Now perform a backward pass on the last variable (NOTE: for each new python variable that you define, call `.retain_grad()`)
7. Print all gradients again

In [54]:
tensor1 = torch.randn(5, 5, requires_grad=True)
tensor1

tensor([[-2.1503,  0.6514, -0.7313,  0.3255,  0.5122],
        [ 0.5282, -0.6753,  1.0182,  1.3142, -0.1672],
        [ 0.8678,  0.2782, -0.5635, -1.2944, -0.4228],
        [ 0.7903,  0.2095, -0.7454, -1.3354,  0.1227],
        [-1.0063,  1.8338, -2.4397, -0.5462, -1.4185]], requires_grad=True)

In [61]:
sum_tens = torch.sum(tensor1)
sum_tens

tensor(-5.0442, grad_fn=<SumBackward0>)

In [63]:
x = tensor1 * 2
x

tensor([[-4.3007,  1.3029, -1.4625,  0.6511,  1.0244],
        [ 1.0563, -1.3506,  2.0364,  2.6284, -0.3343],
        [ 1.7355,  0.5564, -1.1270, -2.5888, -0.8456],
        [ 1.5807,  0.4190, -1.4908, -2.6708,  0.2453],
        [-2.0125,  3.6676, -4.8795, -1.0924, -2.8369]], grad_fn=<MulBackward0>)

In [65]:
sum_x = torch.sum(x)
sum_x

tensor(-10.0883, grad_fn=<SumBackward0>)

In [67]:
x.retain_grad()
sum_x.retain_grad()
print(x.grad)
print(sum_x.grad)

None
None


In [69]:
sum_x.backward()

In [71]:
print(x.grad)
print(sum_x.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor(1.)


### Deep-forward NNs
1. Look at Lab 3. In Exercise 12 there, you had to build an $L$-layer neural network with the following structure: *[LINEAR -> RELU]$\times$(L-1) -> LINEAR -> SIGMOID*. Reimplement the manual code in PyTorch.
2. Compare test accuracy using different optimizers: SGD, Adam, Momentum.

In [2]:
import torch.nn as nn
import torch.nn.init as init
class DeepNeuralNetwork(nn.Module):
    def __init__(self, layer_dims):
        super(DeepNeuralNetwork, self).__init__()
        self.layers = nn.ModuleList()
        for i in range(1, len(layer_dims) - 1):
            linear_layer = nn.Linear(layer_dims[i-1], layer_dims[i])
            init.xavier_uniform_(linear_layer.weight)
            self.layers.append(linear_layer)
            self.layers.append(nn.ReLU())
        self.layers.append(nn.Linear(layer_dims[-2], layer_dims[-1]))
        self.layers.append(nn.Sigmoid())

    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
        return x
    
    def compute_cost(self, predictions, targets):
        criterion = nn.BCELoss()
        return criterion(predictions, targets)
    
    def train_model(self, X_train, y_train, learning_rate=0.01, num_epochs=100, optimizer = "SGD"):
        if optimizer == "SGD":
            optimizer = optim.SGD(self.parameters(), lr=learning_rate)
        elif optimizer == "Adam":
            optimizer = optim.Adam(self.parameters(), lr=learning_rate)
        elif optimizer >=0 and optimizer <=1:
            optimizer = optim.SGD(self.parameters(), lr=learning_rate, momentum = optimizer)
        for epoch in range(num_epochs):
            optimizer.zero_grad()
            predictions = self(X_train)
            cost = self.compute_cost(predictions.T, y_train)
            cost.backward()
            optimizer.step()
            if epoch % 100 == 0:
                print(f'Epoch {epoch}, Cost: {cost.item()}')

In [5]:
from dnn_app_utils_v3 import sigmoid, sigmoid_backward, relu, relu_backward, load_data

train_x_orig, train_y, test_x_orig, test_y, classes = load_data()

# Reshape the training and test examples 
train_x_flatten = train_x_orig.reshape(train_x_orig.shape[0], -1).T   # The "-1" makes reshape flatten the remaining dimensions
test_x_flatten = test_x_orig.reshape(test_x_orig.shape[0], -1).T

# Standardize data to have feature values between 0 and 1.
train_x = train_x_flatten/255.
test_x = test_x_flatten/255.
train_x = train_x.T
test_x = test_x.T
print ("train_x's shape: " + str(train_x.shape))
print ("test_x's shape: " + str(test_x.shape))

train_x's shape: (209, 12288)
test_x's shape: (50, 12288)


In [7]:
layers_dims = [12288, 20, 7, 5, 1] #  4-layer model
train_x = torch.tensor(train_x).float()
train_y = torch.tensor(train_y).float()
test_x = torch.tensor(test_x).float()
test_y = torch.tensor(test_y).float()

In [9]:
import torch.optim as optim
model = DeepNeuralNetwork(layers_dims)

model.train_model(train_x, train_y, learning_rate = 0.0075, num_epochs = 3500)

Epoch 0, Cost: 0.6649003028869629
Epoch 100, Cost: 0.6210528016090393
Epoch 200, Cost: 0.5847263336181641
Epoch 300, Cost: 0.501144528388977
Epoch 400, Cost: 0.44840335845947266
Epoch 500, Cost: 0.3972178101539612
Epoch 600, Cost: 0.3898185193538666
Epoch 700, Cost: 0.21848826110363007
Epoch 800, Cost: 0.1688382774591446
Epoch 900, Cost: 0.26709768176078796
Epoch 1000, Cost: 0.09987503290176392
Epoch 1100, Cost: 0.09863679111003876
Epoch 1200, Cost: 0.04654815047979355
Epoch 1300, Cost: 0.03138680011034012
Epoch 1400, Cost: 0.022983143106102943
Epoch 1500, Cost: 0.01771651767194271
Epoch 1600, Cost: 0.014063948765397072
Epoch 1700, Cost: 0.011512848548591137
Epoch 1800, Cost: 0.009606239385902882
Epoch 1900, Cost: 0.008174281567335129
Epoch 2000, Cost: 0.007032374385744333
Epoch 2100, Cost: 0.00614570640027523
Epoch 2200, Cost: 0.0054223258048295975
Epoch 2300, Cost: 0.004828419536352158
Epoch 2400, Cost: 0.004342368338257074
Epoch 2500, Cost: 0.00393250584602356
Epoch 2600, Cost: 0.00

In [11]:
def accuracy(y_true, y_pred):
    bin_predictions = torch.round(y_pred)
    correct_predictions = torch.sum(bin_predictions.T == y_true)
    accuracy = correct_predictions.item() / y_true.size(1)
    return accuracy
with torch.no_grad():  
    y_test_pred = model(test_x)
    y_train_pred = model(train_x)
print("-"*10 + " SGD optimizer " + "-"*10)
print(f"Test Accuracy:{accuracy(test_y, y_test_pred)}")
print(f"Train Accuracy:{accuracy(train_y, y_train_pred)}")

---------- SGD optimizer ----------
Test Accuracy:0.7
Train Accuracy:1.0


Let's use different optimizer

In [23]:
model2 = DeepNeuralNetwork(layers_dims)
model2.train_model(train_x, train_y, learning_rate = 0.007, num_epochs = 2500, optimizer = "Adam")

Epoch 0, Cost: 0.6990417838096619
Epoch 100, Cost: 0.18245306611061096
Epoch 200, Cost: 0.039969369769096375
Epoch 300, Cost: 0.009613343514502048
Epoch 400, Cost: 0.004065291024744511
Epoch 500, Cost: 0.0022490161936730146
Epoch 600, Cost: 0.0014303084462881088
Epoch 700, Cost: 0.0009895567782223225
Epoch 800, Cost: 0.0007244421285577118
Epoch 900, Cost: 0.0005523400031961501
Epoch 1000, Cost: 0.000434120069257915
Epoch 1100, Cost: 0.0003494447155389935
Epoch 1200, Cost: 0.0002867074799723923
Epoch 1300, Cost: 0.0002389320288784802
Epoch 1400, Cost: 0.00020172017684672028
Epoch 1500, Cost: 0.00017218956782016903
Epoch 1600, Cost: 0.00014836995978839695
Epoch 1700, Cost: 0.0001288892817683518
Epoch 1800, Cost: 0.00011277556768618524
Epoch 1900, Cost: 9.929142106557265e-05
Epoch 2000, Cost: 8.789799176156521e-05
Epoch 2100, Cost: 7.819898019079119e-05
Epoch 2200, Cost: 6.987601955188438e-05
Epoch 2300, Cost: 6.269050936680287e-05
Epoch 2400, Cost: 5.644290285999887e-05


In [25]:
with torch.no_grad():  
    y_test_pred = model2(test_x)
    y_train_pred = model2(train_x)
print("-"*20 + " Adam optimizer " + "-"*20)
print(f"Test Accuracy:{accuracy(test_y, y_test_pred)}")
print(f"Train Accuracy:{accuracy(train_y, y_train_pred)}")

-------------------- Adam optimizer --------------------
Test Accuracy:0.7
Train Accuracy:1.0


In [19]:
model3 = DeepNeuralNetwork(layers_dims)
model3.train_model(train_x, train_y, learning_rate = 0.007, num_epochs = 3000, optimizer = 0.5)

Epoch 0, Cost: 0.6625626683235168
Epoch 100, Cost: 0.6159223914146423
Epoch 200, Cost: 0.5378292798995972
Epoch 300, Cost: 0.3254794180393219
Epoch 400, Cost: 0.13478057086467743
Epoch 500, Cost: 0.04846225678920746
Epoch 600, Cost: 0.02383417822420597
Epoch 700, Cost: 0.014356650412082672
Epoch 800, Cost: 0.009752905927598476
Epoch 900, Cost: 0.007192177232354879
Epoch 1000, Cost: 0.005600974895060062
Epoch 1100, Cost: 0.004532581195235252
Epoch 1200, Cost: 0.0037765668239444494
Epoch 1300, Cost: 0.003216238459572196
Epoch 1400, Cost: 0.002788261277601123
Epoch 1500, Cost: 0.0024496670812368393
Epoch 1600, Cost: 0.002163258381187916
Epoch 1700, Cost: 0.0019151908345520496
Epoch 1800, Cost: 0.0017210772493854165
Epoch 1900, Cost: 0.001561843091621995
Epoch 2000, Cost: 0.0014282675692811608
Epoch 2100, Cost: 0.0013143692631274462
Epoch 2200, Cost: 0.0012161252088844776
Epoch 2300, Cost: 0.001130325486883521
Epoch 2400, Cost: 0.0010547644924372435
Epoch 2500, Cost: 0.0009878413984552026


In [21]:
with torch.no_grad():  
    y_test_pred = model3(test_x)
    y_train_pred = model3(train_x)
print("-"*20 + " Momentum optimizer " + "-"*20)
print(f"Test Accuracy:{accuracy(test_y, y_test_pred)}")
print(f"Train Accuracy:{accuracy(train_y, y_train_pred)}")

-------------------- Momentum optimizer --------------------
Test Accuracy:0.76
Train Accuracy:1.0
